### ISSUE TITLE
the contributors.svg does not work

### ISSUE THREAD

**Issue by wsdjeg** [opencollective/opencollective-api#1164]
I do not know why this svg does not work:

```
<a href="graphs/contributors"><img src="https://opencollective.com/spacevim/contributors.svg?width=890&button=false" /></a>
```

**Comment by monkeywithacupcake** [comment]
The image appears to be working - maybe it was temporary?
![screen shot 2018-03-05 at 14 54 40](https://user-images.githubusercontent.com/7316730/36959426-47748764-2085-11e8-999c-1f84bf089745.png)

**Comment by wsdjeg** [comment]
Thanks，it works now.

**Comment by dooboolab** [comment]
Mine doesn't work too. Should I wait some time?
```
<a href="graphs/contributors"><img src="https://opencollective.com/react-native-iap/contributors.svg?width=890&button=false" /></a>
```

**Comment by monkeywithacupcake** [comment]
I think there is an issue pulling the contributors image right now - I'm getting a not found when I test @dooboolab

**Comment by dooboolab** [comment]
@monkeywithacupcake Any idea how to solve this? Others works fine but mine doesn't..

**Comment by znarf** [comment]
@dooboolab @monkeywithacupcake Everything should work, if you have any issue, please post the address of the SVG that you're having problem with.

**Comment by znarf** [comment]
@lr1d works now.

**Comment by iromise** [comment]
@znarf Hi, https://opencollective.com/ctf-wiki/contributors.svg returns "Not found", and also it does update after a long time..

**Comment by monkeywithacupcake** [comment]
Hi, @iromise - it looks like the image is working now

**Comment by iromise** [comment]
yeah, now it can be shows.. but the number of the people is less than the number of contributor as github shows(https://github.com/ctf-wiki/ctf-wiki/graphs/contributors)...

**Comment by znarf** [comment]
@monkeywithacupcake fixed

**Comment by mlrawlings** [comment]
I'm getting "Not Found" for https://opencollective.com/marko-js/contributors.svg

Wasn't sure if this warranted a new issue as there have been a few urls mentioned in this thread.

**Comment by znarf** [comment]
@mlrawlings looks like your Collective was not active yet. I manually triggered the creation of the badge.

**Comment by Jurabek** [comment]
I am getting not found https://opencollective.com/restaurant-app/contributors.svg

**Comment by WangJiangJiaoZi** [comment]
@znarf  https://opencollective.com/reixs/contributors.svg returns "Not found"

**Comment by MingliangT** [comment]
Hi @znarf [https://opencollective.com/rdebug/contributors.svg](https://opencollective.com/rdebug/contributors.svg?width=890&button=false) return "Not found"

**Comment by panjf2000** [comment]
@znarf 
Hi,
I am reporting that the contributors.svg of my GitHub repositories doesn't work, returning "Not found".

https://opencollective.com/ants/contributors.svg

https://opencollective.com/gnet/contributors.svg

**Comment by vivaxy** [comment]
@znarf [https://opencollective.com/gacp/contributors.svg](https://opencollective.com/gacp/contributors.svg) does not work.

**Comment by dlhandsome** [comment]
Hi,  @znarf  https://opencollective.com/we-cropper/contributors.svg return "Not found"

**Comment by gqcn** [comment]
@znarf My contributor svg shows "Not Found", should I wait some time? A crontab job?
https://opencollective.com/gf/contributors.svg

**Comment by marqbeniamin** [comment]
Hi @znarf https://opencollective.com/vue-material/contributors.svg return "Not Found"!

**Comment by TheKhaeng** [comment]
Hi @znarf https://opencollective.com/gui-ui-guideline/contributors.svg return "Not found"
