### ISSUE TITLE
banner.js not pulling sponsors

### ISSUE THREAD

**Issue by monkeywithacupcake** [opencollective/opencollective-api#1165]
Widget for backers and sponsors results in error 

**ISSUE**
When using this script:
```<script src="https://opencollective.com/:collectiveSlug/banner.js"></script>``` to show backers and sponsors, nodemailer is getting an error. 

**EXPECTED RESULT**
Backers and sponsors should show

**ACTUAL RESULT**
Can be seen at bottom of left blue sidebar on [nodemailer](https://nodemailer.com/about/)
![screen shot 2018-03-05 at 14 59 24](https://user-images.githubusercontent.com/7316730/36959519-d5368ff2-2085-11e8-8c87-6f60f0974b67.png)

**Comment by znarf** [comment]
@monkeywithacupcake Looks like it's working great again. Not sure what happened back then.

**Comment by znarf** [comment]
Closing.
