### ISSUE TITLE
Refresh test dbdumps

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-api#1314]
As mentioned in this issue https://github.com/opencollective/frontend/issues/467, it looks like the dbdumps are outdated.

Is there a way to refresh them?

**Comment by clarete** [comment]
I don't think we have a working solution for seeding data into our dev database. We only have some tools for updating the schema of the binary dumps and some scripts to copy the production database to a local one and scramble sensitive data.

Although we have thought about keeping a binary dump to allow people to see some content when they setup open collective, I wonder if there's an easier way of doing it.

**Comment by HipsterBrown** [comment]
I'm going to try replacing the dbdumps with Sequelize seeder files to enable easier refreshing of local data and a reliable getting started experience.
