### ISSUE TITLE
lib/currency: can't fetch fxrate from EUR to USD for date latest

### ISSUE THREAD

**Issue by Betree** [opencollective/opencollective-api#1319]
A friend of mine just encountered this error while trying to donate to https://opencollective.com/captainfact_io :

![bug_message](https://user-images.githubusercontent.com/1556356/40931885-faef3c5a-682c-11e8-8f57-a57ce6d0e34f.png)

Please tell me if you need more info and I'll ask him

**Comment by piamancini** [comment]
yes, someone else just reported the same for CAD 
![screen shot 2018-06-04 at 1 54 00 pm](https://user-images.githubusercontent.com/3671070/40933761-78c8f080-6800-11e8-8a44-67affb0fcb90.png)

**Comment by piamancini** [comment]
cc/ @xdamman @znarf

**Comment by znarf** [comment]
An API we're using just deprecated their old version, we need to update and upgrade to one of their paid plan. https://github.com/fixerAPI/fixer

PR in progress: https://github.com/opencollective/opencollective-api/pull/1320

**Comment by Betree** [comment]
Would be nice to have a local cache of these data, this kind of thing could happen again in the future with network errors or if their service goes down :wink:

**Comment by znarf** [comment]
It's actually cached, but only in process memory. So it's wiped on restart. We can do better ;-)

That should be fixed in production now.

**Comment by Betree** [comment]
@znarf Murphy's law :slightly_smiling_face: Quick response on the issue, well done.
