### ISSUE TITLE
AddMissingBackers migration failing 

### ISSUE THREAD

**Issue by znarf** [opencollective/opencollective-api#1386]
`ERROR: null value in column "CreatedByUserId" violates not-null constraint`

To reproduce:

- `dropdb opencollective_dvl`
- ` ./scripts/postinstall.sh` (restore the database)
- ` ./scripts/postinstall.sh` (run the migration)

**Comment by xdamman** [comment]
Ah, I didn't see this issue (I should double check my notification settings)
I fixed this already last week in https://github.com/opencollective/opencollective-api/pull/1388
