### ISSUE TITLE
pull stats for "soft" contributions to repositories

### ISSUE THREAD

**Issue by boneskull** [OpenCollective/opencollective-api#327]
Prompted by @dasilvacontin's [comment](https://github.com/OpenCollective/OpenCollective/issues/33#issuecomment-217286369)

This means adding comments, adding issues, sending PRs (which are not necessarily merged), and generally any other activity than just committing code (someone please confirm my assumption here).

**Comment by dasilvacontin** [comment]
Closing issues, heh.
