### ISSUE TITLE
Bug in the documentation

### ISSUE THREAD

**Issue by HeaTTheatR** [opencollective/opencollective-api#4552]
Hello!
I am writing to you about a bug in the documentation - https://docs.opencollective.com/help/contributing/development/api/users-emails

![Снимок экрана 2020-09-11 в 17 46 20](https://user-images.githubusercontent.com/16930280/92965229-1692d680-f47e-11ea-9ba5-24531da175b3.png)
![Снимок экрана 2020-09-11 в 17 47 21](https://user-images.githubusercontent.com/16930280/92965247-1b578a80-f47e-11ea-8ca6-1eb726566802.png)

I tried to use the this API with my accesssToken of administrator in the KivyMD collective - https://opencollective.com/kivymd
I tried to get information about the backer of the KiviMD team using an API:

`curl -H "Authorization: Andrew myAccesssToken" https://opencollective.com/api/groups/kivymd/users`

This returns "Not Found".
Maybe I'm doing something wrong?
Thank!

**Comment by znarf** [comment]
We're not supporting this endpoint anymore, it should have been removed from the documentation.

We're generally recommending to use our GraphQL API v2 for everything.

**Comment by znarf** [comment]
@HeaTTheatR Feel free to ask on Slack if you need help on using the GraphQL API.
