### ISSUE TITLE
Tracking community engagement

### ISSUE THREAD

**Issue by btopro** [opencollective/opencollective-api#793]
Was curious if you've thought of a way of tracking and promoting those who engage with communities that they support / contribute to the collective directly in site content form / commits downstream to repos that feed it, money (which I know you "track" in some form). I bring this up because I think you could build a bit of an engagement / tracking engine pretty easily or at least worth thinking about thanks to a standard called xAPI.

xAPI is short for Experience API. It's popular in training / education but also with analytics / advertising people. There's also a great open source xAPI store (in industry called LRS) which might be willing to get involved in exchange for the benefits this group provides -- https://learninglocker.net/

If you want to learn more about xAPI, here's some stuff assembled about xAPI in a public elmsln space I'm working on https://courses.openulmus.org/xapi/

Basic idea: Track activity / everything people do back from distributed places to centralized LRS (learning locker). Then query the engine nightly (or weekly or whatever) and email reports to people in open collective highlighting who had the most engagement that week, who contributed the most money, etc.

**Comment by piamancini** [comment]
@xdamman you might be interested in this

**Comment by xdamman** [comment]
Yes we would love to have an easy way to create monthly activity reports for backers. 
See also https://github.com/OpenCollective/OpenCollective/issues/312#issuecomment-279915527

Ideally, we should have "plugins". Eg a plugin for github.com, one for Facebook, medium, meetup.com, etc.

Each of those plugins would create a monthly digest for the collective. This would include:
- a short summary:
Webpack had 10 new issues, 7 new pull requests and 30 new comments. 
- a digest:
Top issues this month: 
  - release of webpack 2.0 (20 comments)
  - now you can order your webpack swag (12 comments)
Latest release notes: 
  - xxxx 
   - etc. 

You could imagine the same with the number of meetups and number of people who signed up for them, most popular posts shared on twitter or Facebook by the collective, totally number of engagement through comments and likes. Etc. 

Feel free to prototype one of those plugins for the platform of your choice. This could be the base for others to build other plugins. Let me know what you need.

**Comment by gusaus** [comment]
I referenced this and #769 as potential components the Drupal community could use to sustain projects. http://buytaert.net/comment/130991#comment-130991

Based on the feedback from the founder of the project others in the community, I think Drupal would be a good test case.

**Comment by gusaus** [comment]
@btopro What about running a learning program built on https://www.elmsln.org/ to prove some concepts and even work on some of these integrations? I could see OpenCollective as a tool for funding those putting together tutorials, curriculum, or training programs.

**Comment by btopro** [comment]
@gusaus That's kind of my vision w/ OpenUlmus as a Free deploy that's community supported and has free "courses" / training. Are you thinking that this could be funded by OpenCollective to cover costs of hosting or you mean like pay contributors to build tutorials in the system or what?

I'd be open to helping get that going w/ some idea of a roadmap and realization that I fall off the map when we get in crunch periods of contribution to the tool itself :)

**Comment by gusaus** [comment]
@btopro All of the above! One of the goals of https://opencollective.com/drupalopenlearning, still in limbo, is to provide a way to sustain a community supported, free, learning program for Drupal. Funds could be allocated to the people developing/maintaining the website and managing the program, and covering other costs like hosting.

OpenCollective could also be an option for those needing funds to create their own training program , curriculum, tutorials, etc. Ideally this functionality would be built into the system where users would be able to create their own campaign.

Probably don't want to get too into the weeds in this issue (I've already set up the topic in Slack), but with ELMS also running on Drupal, it seems like a good project to test the waters in the open and engage the community.

**Comment by znarf** [comment]
We're currently iterating and updating older issues. Unfortunately we have no plan to support that in the immediate future.
