### ISSUE TITLE
Have the API include the email or hashed email identifier of backers

### ISSUE THREAD

**Issue by balupton** [opencollective/opencollective-api#849]
Currently the only identifiable information Open Collective provides in the API responses, is that which may or may not be provided by clearbit's analytics. If the API user is building an application where they must link a users identity against their opencollective account, the irregularity of verified identifiers makes this impractical.

I spoke with @xdamman a few weeks ago about the API about requesting the API to return the email addresses of the backers. He correctly responded that this is not done, as the emails are sensitive information. 

One solution is a secret token approach, where the API user can provide an account token, that when provided, will expose the email addresses of their backers - however this remains an issue, as the backers may not want their emails seen even by the groups they are backing

A new solution I thought of is to hash the emails, and have the algorithm public, and if a salt is used, then have it something that the API user can know (if a salt is desired, can probably just be the username of the organisation that is being backed). This will ensure the emails remain private, while allowing API users to verify, identify, and consequently link open collective backers against their own app's users.

For the hashing, I'm quite a fan of blake2

**Comment by xdamman** [comment]
Have a look at the new #api channel on https://slack.opencollective.org

We plan to create shadow users so that we can have tokens to access the API. You will have access to the email addresses if you are registered as a core contributor of a collective. Users expect to be able to be reached by the collectives they belong to / contribute to (it's also in our privacy policy).

**Comment by znarf** [comment]
Emails are now effectively exposed for the admin of the collectives.

I'm closing the issue as there is no traction for it right now. We will reopen if the topic come back.
