### ISSUE TITLE
Switching event template makes form disappear

### ISSUE THREAD

**Issue by alannallama** [opencollective/opencollective-api#913]
I was going through the process of creating an event in testcollective, and I switched from "no template" to "test template" to see what would happen. All the rest of the form fields and buttons disappeared and I can't get them back (switching back to 'no template' doesn't help).

![screenshot 1](https://user-images.githubusercontent.com/5498878/28256480-ec88cb68-6b16-11e7-8792-87b0da5a45aa.png)

**Comment by clarete** [comment]
I guess this is also old. Please reopen if that's still happening
