### ISSUE TITLE
[feature request] transparent avatars in backers & sponsors widget

### ISSUE THREAD

**Issue by KagamiChan** [opencollective/opencollective-api#921]
I'm placing backers & sponsors widget on a page with dark background, and find out that some avatars are not transparent, like this:

![image](https://user-images.githubusercontent.com/3816900/30779477-9b0bac12-a124-11e7-9cc9-2442a96b8d62.png)

Could this widget embeds png format avatar images so that the white corner is removed? Or am I missing some control parameters?

-----
Moved from opencollective/opencollective#419

**Comment by piamancini** [comment]
cc @xdamman

**Comment by clarete** [comment]
I'm closing this ticket since it's documented in the our main issues tracker: opencollective/opencollective
