### ISSUE TITLE
GraphQL error: No collective found with slug undefined

### ISSUE THREAD

**Issue by yeskunall** [opencollective/opencollective-api#926]
I just signed up for an account. I'm able to log in, but as soon as I try going to my profile, I get this:

![image](https://user-images.githubusercontent.com/14703164/31298570-be4cd5d2-aab8-11e7-9116-54416caf8e21.png)

I know `v2` just went live, so this might be a bug no one's caught yet. Thought you guys should know. Issue stems from this:

https://github.com/opencollective/opencollective-api/blob/74d07d7e91d977757f4665cf7a8adfd7d10a5213/server/models/Collective.js#L925-L936

**Comment by xdamman** [comment]
Thanks for taking the time to report this issue. Not sure yet what's causing this exactly.
In the meantime, your profile page is https://opencollective.com/yeskunall

**Comment by xdamman** [comment]
What flow did you follow to sign up? I don't see any transaction under your account. You simply hit "login" and then entered your email address?

**Comment by yeskunall** [comment]
Hit login on `/` of @opencollective, then entered email address. Was told current email doesn't exist. So I signed up. Here, this _might_ help: opencollective/opencollective-website#764.

**Comment by xdamman** [comment]
Fixed
