### ISSUE TITLE
svg does not work anymore

### ISSUE THREAD

**Issue by pleerock** [opencollective/opencollective-api#937]
I have following code:

```
## Contributing 

Learn about contribution [here](CONTRIBUTING.md) and how to setup your development environment [here](DEVELOPER.md).

This project exists thanks to all the people who contribute:

<a href="graphs/contributors"><img src="https://opencollective.com/typeorm/contributors.svg?width=890" /></a>


## Backers 🙏

Thank you to all our backers! If you want to support a project and become a backer [click here.](https://opencollective.com/typeorm#backer)

<a href="https://opencollective.com/typeorm#backers" target="_blank"><img src="https://opencollective.com/typeorm/backers.svg?width=890"></a>


## Sponsors 🤑

Support this project by becoming a sponsor. Your logo will show up here with a link to your website. [Become a sponsor](https://opencollective.com/typeorm#sponsor)

<a href="https://opencollective.com/typeorm/sponsor/0/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/0/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/1/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/1/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/2/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/2/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/3/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/3/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/4/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/4/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/5/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/5/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/6/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/6/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/7/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/7/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/8/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/8/avatar.svg"></a>
<a href="https://opencollective.com/typeorm/sponsor/9/website" target="_blank"><img src="https://opencollective.com/typeorm/sponsor/9/avatar.svg"></a>
```

which does not work anymore (I guess something broke after opencollective updating?) I don't have Backers or Sponsors 😭  so I cannot confirm if they work, but I do have contributors and they aren't shown anymore.

Not sure if its a correct repository to report this issue.

**Comment by piamancini** [comment]
Thank you @pleerock We are working on a fix. We'll let you know as soon as it's done. 
best!

**Comment by piamancini** [comment]
hi @pleerock we just pushed a fix. Can you please confirm this is solved? thanks!

**Comment by pleerock** [comment]
Nope, it does not. If enough to check if it works by following this link https://opencollective.com/typeorm/contributors.svg?width=890 which should return svg code, but now it returns 404.

**Comment by piamancini** [comment]
ok. We are tracking it here https://github.com/opencollective/opencollective/issues/479

**Comment by xdamman** [comment]
Fixed.

**Comment by dooboolab** [comment]
@xdamman Could you check mine also? https://opencollective.com/react-native-iap/contributors.svg?width=890. It is not found for 3 days now.

**Comment by marcogbarcellos** [comment]
@xdamman , I tried taking a quick look on it last week but didnt spend a lot of time, should we prioritize this for this week? If yes, i can spend some more time

**Comment by dooboolab** [comment]
How can I make mine work? I've sent email to `opencollective` and no response for long time. I'm having trouble now. Could someone suggest me any solution?

**Comment by marcogbarcellos** [comment]
hey @dooboolab sorry to hear that, we have noticed this last week and will try to solve soon. I will keep this issue(as well as you) posted. once more, sorry to hear that and we'll hopefully have it done quite soon.

**Comment by papnoisanjeev** [comment]
@piamancini  we have setup our account  https://opencollective.com/uvdesk
but we are not able to see contributors list after link opencollective with our github account.
we want to use contributors svg src in our project.
