### ISSUE TITLE
"Become a backer" image not found

### ISSUE THREAD

**Issue by lex111** [opencollective/opencollective-api#943]
"Become a backer" picture gives 404 error.

[CONTRIBUTING.md](https://github.com/gitpoint/git-point/blob/master/CONTRIBUTING.md#backers)
[Image link](https://opencollective.com/git-point/backers.svg?width=890) - 404, although previously shown

**Comment by piamancini** [comment]
Thanks @lex111 we are working on a fix. issue opened here: https://github.com/opencollective/opencollective/issues/479

**Comment by xdamman** [comment]
Fixed
