### ISSUE TITLE
Development area setup api_key missing

### ISSUE THREAD

**Issue by MagdeburgerBruck** [opencollective/opencollective-api#960]
README.md file mentions `cp $DROPBOX/OpenCollective/Engineering/Keys/config/DOTenv .env` but no variable $DROPBOX appears anywhere defined. On `npm run start`, output contains:

`Error: ENOENT: no such file or directory, open '.env'`

Unless a blank file is created manually.

The output from the API itself is then:

```
error | 
-- | --
code | 400
type | "missing_required"
message | "Missing required fields"
fields |  
api_key | "Required field api_key missing"

```

How is it possible to contribute to the library when the required configuration details are not available...

**Comment by asood123** [comment]
There is a default.env file in the repo that should get picked up. I haven't tried it on a new repo in a while, so it's possible it broke. You can try renaming that to .env and see if it works. The error shouldn't be a show stopper otherwise.

**Comment by asood123** [comment]
Let me know if it still doesn't work for you. We might need to add a couple of additional entries in default.env to get past this step.

**Comment by clarete** [comment]
I'm closing this one as #1204 was merged and it should be pretty straight forward to run the whole environment with one command now!
