### ISSUE TITLE
/groups/xxx/backers API broken because of recent change

### ISSUE THREAD

**Issue by sokra** [opencollective/opencollective-api#967]
This change https://github.com/opencollective/opencollective-api/commit/0cb49a6395e780e2cd28be1cd7a043b041b80b3f#diff-b636168bbbc25aab3b1866cf4c10fc7aR426 changes the default LIMIT to 100 items.

This breaks this API https://github.com/opencollective/opencollective-api/blob/master/server/routes.js#L158 which now only returns the first 100 items instead of all.

We recently added a plausibility verification to our CI builds of webpack.js.org because of the often breaking/changing API, so this also breaks the deployment of the documentation https://travis-ci.org/webpack/webpack.js.org/builds

**Comment by xdamman** [comment]
Sorry about that breaking change. I didn't realize it was going to be a problem.
Deploying a quick fix now, but we should find a more sustainable solution for the future. Maybe a Graphql call to make sure you only fetch the data that you need would work better.

**Comment by sokra** [comment]
Thanks
