### ISSUE TITLE
New member welcome email says it comes from the recipient / doesn't CC inviter

### ISSUE THREAD

**Issue by paulmelnikow** [opencollective/opencollective-api#996]
Hi there, cool project!

I was just added to a new collective by one of my co-maintainers. The email notification I received was confusing.

> Paul Melnikow added you as a admin to shields collective on Open Collective

> Paul Melnikow, Just a quick note to let you know that Paul Melnikow (cced) added you as a admin to shields collective on Open Collective. As a core contributor you have ADMIN permissions. That means that you can approve and reject expenses that have been submitted to your collective. You can do so with one click from the email notification or via the interface on https://opencollective.com/shields/expenses.

The expected notification would be:

> Thaddée Tyl added you as a admin to shields collective on Open Collective

> Paul Melnikow, Just a quick note to let you know that Thaddée Tyl (cced) added you as a admin to shields collective on Open Collective. As a core contributor you have ADMIN permissions. That means that you can approve and reject expenses that have been submitted to your collective. You can do so with one click from the email notification or via the interface on https://opencollective.com/shields/expenses.

I found the notification template:

https://github.com/opencollective/opencollective-api/blob/a46dbf74acb53be75669332dd28c96059a6de1c7/templates/emails/collective.newmember.hbs

And the code that triggers it:

https://github.com/opencollective/opencollective-api/blob/16697c00fb9a978b7641d09e36d60fbda83b5e53/server/models/Collective.js#L478-L499

Then I'm lost. The problem isn't obvious. Any suggestions how to diagnose this, test it, or where to dig in further?

**Comment by piamancini** [comment]
Thank you @paulmelnikow! Assigning this to @xdamman

**Comment by oanabotezat** [comment]
seems to be like this thicket is also resolved and should be closed.

**Comment by xdamman** [comment]
Good catch. Closing.
